# LlamaFit. Copyright (C) 2026 Paulo Vaz.
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of LlamaFit; see LICENSE for the full terms and the warranty disclaimer.
"""Typed data shared by every layer of LlamaFit."""

from llamafit.models.catalog import (
    ArchClass,
    Architecture,
    Benchmark,
    Capability,
    Catalog,
    CatalogModel,
    ChatTemplate,
    Context,
    Extra,
    ExtraRole,
    License,
    LlamaCppNeeds,
    Measured,
    ModelSource,
    Params,
    Quality,
    Quant,
    Sampling,
    Trust,
    UseCase,
)
from llamafit.models.gguf import GgufFacts, GgufHeader, TensorInfo
from llamafit.models.host import (
    Arch,
    Backend,
    Cpu,
    Disk,
    Gpu,
    Host,
    MachineFacts,
    Memory,
    OsName,
    Override,
    Probe,
    Simulation,
    Source,
    Vendor,
    machine_facts,
)
from llamafit.models.hwprofile import (
    PROFILE_SCHEMA_VERSION,
    HardwareProfile,
    ProfileCalibration,
    ProfileCpu,
    ProfileGpu,
    ProfileMatch,
    ProfileMemory,
)
from llamafit.models.llamacpp import LlamaCpp, LocalModel, RunningServer
from llamafit.models.report import SystemReport

__all__ = [
    "PROFILE_SCHEMA_VERSION",
    "Arch",
    "ArchClass",
    "Architecture",
    "Backend",
    "Benchmark",
    "Capability",
    "Catalog",
    "CatalogModel",
    "ChatTemplate",
    "Context",
    "Cpu",
    "Disk",
    "Extra",
    "ExtraRole",
    "GgufFacts",
    "GgufHeader",
    "Gpu",
    "HardwareProfile",
    "Host",
    "License",
    "LlamaCpp",
    "LlamaCppNeeds",
    "LocalModel",
    "MachineFacts",
    "Measured",
    "Memory",
    "ModelSource",
    "OsName",
    "Override",
    "Params",
    "Probe",
    "ProfileCalibration",
    "ProfileCpu",
    "ProfileGpu",
    "ProfileMatch",
    "ProfileMemory",
    "Quality",
    "Quant",
    "RunningServer",
    "Sampling",
    "Simulation",
    "Source",
    "SystemReport",
    "TensorInfo",
    "Trust",
    "UseCase",
    "Vendor",
    "machine_facts",
]
