"""Write MODELS.md, the public model catalog page, from the curated catalog.

Usage:
    python scripts/gen_models_md.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from llamafit.catalog import load_catalog
from llamafit.models.catalog import Architecture, Catalog, CatalogModel, Context, License, Params

DEST = Path(__file__).resolve().parents[1] / "MODELS.md"

_ARCHITECTURE_LABELS = {
    "dense": "Dense",
    "moe": "MoE",
    "dense-hybrid": "Dense-hybrid",
    "moe-hybrid": "MoE-hybrid",
}

_COLUMNS = ("Model", "Parameters", "Architecture", "Context", "Capabilities", "Licence", "Quants")


def _escape_cell(text: str) -> str:
    """Make free text safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _format_b(value: float) -> str:
    """Format a parameter count in billions without a spurious ``.0``."""
    return str(int(value)) if value.is_integer() else f"{value:g}"


def _render_model_cell(model: CatalogModel) -> str:
    """The display name plus the id every command actually takes, in backticks."""
    return f"{_escape_cell(model.name)} (`{model.id}`)"


def _render_params(params: Params) -> str:
    """Total parameters, and active parameters too when they differ (a MoE model)."""
    total = _format_b(params.total_b)
    if params.active_b == params.total_b:
        return f"{total}B"
    return f"{total}B total / {_format_b(params.active_b)}B active"


def _render_architecture(architecture: Architecture) -> str:
    """A human label for the architecture class, falling back to the raw value."""
    return _ARCHITECTURE_LABELS.get(architecture.class_, architecture.class_)


def _render_context(context: Context) -> str:
    """Native context length, plus the extended length and method when there is one."""
    text = f"{context.native:,}"
    if context.extended:
        via = f" via {context.extended_method}" if context.extended_method else ""
        text += f" (up to {context.extended:,}{via})"
    return text


def _render_capabilities(model: CatalogModel) -> str:
    """Capabilities in curated order, not resorted."""
    return ", ".join(model.capabilities)


def _render_licence(license_: License) -> str:
    """The licence identifier, linked to the actual licence text."""
    return f"[{_escape_cell(license_.spdx)}]({license_.url})"


def _render_quants(model: CatalogModel) -> str:
    """Curated quant names only.

    Sizes and checksums are filled in later by a refresh command that has not run
    yet; naming only the quant lets this column stay correct once it has.
    """
    names: list[str] = []
    for source in model.sources:
        for quant in source.quants:
            if quant.name not in names:
                names.append(quant.name)
    if not names:
        return "unknown"
    return ", ".join(f"`{_escape_cell(name)}`" for name in names)


def _render_header(example_id: str | None) -> str:
    """The page's header: what this is, and how to read the identifier in each row.

    Args:
        example_id: A real catalog id to name in a worked example, or ``None`` when
            the catalog has no models to draw one from.

    Returns:
        The header, as one Markdown paragraph under a title.
    """
    text = (
        "# LlamaFit Model Catalog\n\n"
        "This page is generated by `scripts/gen_models_md.py` from the catalog under "
        "`src/llamafit/data/catalog/`. Do not edit it by hand: changes will be overwritten "
        "the next time the script runs."
    )
    if example_id is not None:
        text += (
            " Each model's identifier, shown in backticks after its name, is what every "
            f"command takes, for example `llamafit info {example_id}`."
        )
    return text


def _render_table(models: list[CatalogModel]) -> str:
    """A Markdown table for one vendor's models, already sorted by the caller."""
    lines = [
        f"| {' | '.join(_COLUMNS)} |",
        f"|{'|'.join(['---'] * len(_COLUMNS))}|",
    ]
    for model in models:
        cells = (
            _render_model_cell(model),
            _render_params(model.params),
            _render_architecture(model.architecture),
            _render_context(model.context),
            _render_capabilities(model),
            _render_licence(model.license),
            _render_quants(model),
        )
        lines.append(f"| {' | '.join(cells)} |")
    return "\n".join(lines)


def render_markdown(catalog: Catalog) -> str:
    """Render the full page: the header, then one table per vendor, both sorted."""
    vendors = sorted({model.vendor for model in catalog.models})
    grouped = [
        (vendor, sorted((m for m in catalog.models if m.vendor == vendor), key=lambda m: m.id))
        for vendor in vendors
    ]
    example_id = grouped[0][1][0].id if grouped else None
    sections = [_render_header(example_id)]
    for vendor, models in grouped:
        sections.append(f"## {vendor}\n\n{_render_table(models)}")
    return "\n\n".join(sections) + "\n"


def main() -> int:
    """Regenerate MODELS.md and report where it went.

    Refuses to write anything if the catalog has problems: a published page with a
    gap in it is worse than no page, so this fails loudly and names every model and
    problem instead.
    """
    catalog, problems = load_catalog()
    if problems:
        for problem in problems:
            model = problem.model_id or "(unknown model)"
            print(
                f"{problem.file}: {model}: {problem.location}: {problem.message}",
                file=sys.stderr,
            )
        print(
            f"refusing to write {DEST.name}: the catalog has {len(problems)} problem(s)",
            file=sys.stderr,
        )
        return 1
    DEST.write_text(render_markdown(catalog), encoding="utf-8")
    print(f"wrote {DEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
