"""Record this machine's probe outputs as a test fixture module.

Usage:
    python scripts/record_fixtures.py my-machine > tests/fixtures/my_machine.py

The generated module exposes ``runner()``, ``cpuinfo()``, ``vm()`` and ``cores()`` in the same
shape as ``tests/fixtures/reference_machine.py`` so a scan test can reproduce the machine
without it. ``cores()`` matters: a test that leaves it out reads the core count of whatever
machine runs the test, and then asserts values that only hold on the recorder's machine.
"""

from __future__ import annotations

import pprint
import sys
from collections.abc import Mapping, Sequence

import psutil

from llamafit.hardware import current_os
from llamafit.hardware import gpu as gpu_probes
from llamafit.hardware import memory as memory_probes
from llamafit.hardware.runner import SubprocessRunner

# Private constants are imported on purpose: the recorder must run exactly what the probes run.
_COMMON: dict[str, Sequence[str]] = {
    "nvidia-smi": gpu_probes._NVIDIA_CMD,
    "rocm-smi": gpu_probes._ROCM_CMD,
}
_BY_OS: dict[str, dict[str, Sequence[str]]] = {
    "windows": {
        "wmi-video": gpu_probes._WMI_CMD,
        "memory-modules": memory_probes._WINDOWS_MODULES_CMD,
    },
    "macos": {
        "system-profiler": gpu_probes._APPLE_CMD,
        "memory-modules": memory_probes._MACOS_MEMORY_CMD,
        "sysctl-perflevel": ["sysctl", "-n", "hw.perflevel0.physicalcpu"],
    },
    "linux": {
        "lspci": gpu_probes._LSPCI_CMD,
        "memory-modules": memory_probes._LINUX_MEMORY_CMD,
    },
}


def collect(runner: SubprocessRunner, os_name: str) -> dict[str, str]:
    """Run every probe command for this OS and keep the stdout of the ones that worked."""
    commands = {**_COMMON, **_BY_OS[os_name]}
    responses: dict[str, str] = {}
    for name, argv in commands.items():
        result = runner.run(argv, timeout=20.0)
        if result.ok:
            responses[" ".join(argv)] = result.stdout
        else:
            reason = result.error or f"exit code {result.returncode}"
            print(f"# {name}: skipped ({reason})", file=sys.stderr)
    return responses


def build_module(
    name: str,
    responses: Mapping[str, str],
    cpuinfo: Mapping[str, object],
    vm: tuple[int, int],
    os_name: str,
    cores: tuple[int, int],
) -> str:
    """Render the fixture module source for the recorded data."""
    docstring = (
        f'"""Recorded probe outputs from {name} ({os_name}). '
        'Generated by scripts/record_fixtures.py."""'
    )
    lines = [
        docstring,
        "",
        "from llamafit.hardware.runner import FakeRunner",
        "",
        f"OS_NAME = {os_name!r}",
        "",
        "RESPONSES = " + pprint.pformat(dict(responses), width=100, sort_dicts=True),
        "",
        "CPUINFO = " + pprint.pformat(dict(cpuinfo), width=100, sort_dicts=True),
        "",
        f"VM = {vm!r}",
        "",
        f"CORES = {cores!r}",
        "",
        "",
        "def runner() -> FakeRunner:",
        "    return FakeRunner(RESPONSES)",
        "",
        "",
        "def cpuinfo() -> dict[str, object]:",
        "    return dict(CPUINFO)",
        "",
        "",
        "def vm() -> tuple[int, int]:",
        "    return VM",
        "",
        "",
        "def cores() -> tuple[int, int]:",
        "    return CORES",
        "",
    ]
    return chr(10).join(lines)


def main(argv: Sequence[str]) -> int:
    """Entry point."""
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 1
    import cpuinfo as cpuinfo_lib

    os_name = current_os()
    info = cpuinfo_lib.get_cpu_info()
    cpu = {"brand_raw": info.get("brand_raw", ""), "flags": list(info.get("flags", []))}
    memory = psutil.virtual_memory()
    responses = collect(SubprocessRunner(), os_name)
    vm = (int(memory.total), int(memory.available))
    cores = (int(psutil.cpu_count(logical=False) or 0), int(psutil.cpu_count(logical=True) or 0))
    sys.stdout.write(build_module(argv[1], responses, cpu, vm, os_name, cores))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
