import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def load_script():  # type: ignore[no-untyped-def]
    script_path = ROOT / "scripts" / "record_fixtures.py"
    spec = importlib.util.spec_from_file_location("record_fixtures", script_path)
    module = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def test_build_module_is_importable_python() -> None:
    script = load_script()
    cpuinfo = {"brand_raw": "x", "flags": ["avx2"]}
    source = script.build_module("box", {"nvidia-smi -L": "GPU 0"}, cpuinfo, (16, 8), "linux")
    namespace: dict[str, object] = {}
    exec(compile(source, "fixture", "exec"), namespace)  # generated by our own code, not user input
    assert namespace["runner"]().run(["nvidia-smi", "-L"]).stdout == "GPU 0"  # type: ignore[operator]
    assert namespace["vm"]() == (16, 8)  # type: ignore[operator]
